### ISSUE TITLE
node module not updated on www.npmjs.com

### ISSUE THREAD

**Issue by orlando-antonino** [jo32/grunt-cache-invalidate#3]
Hi, installing this module through npm package manager grunt-cache-invalidate module is not updated. The difference is in the 
```javascript
   function isPathEqual(p1, p2) {
        return path.normalize(p1) === path.normalize(p2);
    }
```
the git version has a fix:
```javascript
       return path.normalize(p1.toString()) === path.normalize(p2.toString());
```

could you please update?
Thanks

**Comment by jo32** [comment]
Hi, you can do a pull request next time.

Thank you for your report of this bug.
